language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean source:jar deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique-swagger "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-swagger "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "raB9UtHxJuE5ef+prGGCvXsxt6pgVV3CMHIQfTzacIq2LV3bWCtfLG6ddBiUHEqhHx4GylvtoNXa1WVwsO0CxHQIjNXx0tYcfr5RBgb7DQW+mJOv09iTnNNWF06uxxel4pXVyBYxwvzdWDHMy13dA0LtxX11belR+eFPrS3NHE+BlDc4xuMCy7BpQsXUy3jyyl26YWJbEQfRjiJPkLQ8RYDkp1B7EpfJQPmhiOvrUG2FdeinLvpOA/PQEYujziKBOvRzZ5Vx3yfepRUIITENPAHo6tW4MtSQqSFLrIvxp7Eeoftf+q/agPZHKbyW2uCgD9/Dan+hJMAZe3gTIVFmdoIv6BKuEIW0/lZiA4JrcOGK6gMORsCqSex07OXvs6RJz75PcjGL2GUQ+r+WuPICWPcdFNVDfcalN0xwyqa+OAvrP7fzgWVkgI41iOpWWpTr85uuZRFgX2bQompg5ToI3Kwt7pr/93+OcTVtFlP5sQvpIHKRgt4b3TytsTPcKeh66LzJDLHi3nOnB9n0/fXCPt3JvBH73znu95niSkJFPUY7J0wdRQpiKW7QC+xBMWLoEjuNySkKCGnjn/1coSoXzYlK5rmDNFkPgIiPsLnxHzmjG71vcZwkbO8a+peccUWSCA0+Nmr82lNunscS2nbvZJCm7oQ0TCD6tiYlKAcrUBY="
    - secure: "DR68pnbRjX2WdmtfBQwmwGPO+l8F0lAHY7gpl/ECgJTBBBpBiAZFoII5xdFdMx4xDj4umm3gtG/XcmA4s1DCy9JMYYYilkZHj05oWliMjY2q3qyX/ifgwlNI0cYXVeNK10dTGhGCPjBfcMueoX946BWvRrA5P63vX6QUSlqmMYsSpVkVl3gS5MA8cVYsW9JTPmHnFFkL4dpNkr3QrtixCrjIlsdONM4/uOxwPwuKE59/vgxCQIPp3vtyhf+mnKw8PSSS9TaQSWpXswY+t+pYXEJHToZwEx671mkFSkaFtTK2z8tyv2WjiJ0GtdsEJi6Cl/XWAfcYrbYKiF8zmSxGIo/5uMq8HeVtAvtEsdlSyHDYNqCOoVM38X9MTcTB3r8wZ3KlLGeO1xRt+zDOu3fgSFiuCr4H9pIKEcvc36o6j/aM8ry7CCENu+5dcYdpKImA5SffrQHKDQeCVaz9zILgLOCXMGUfUQnf+B3c0v+KMd2pMs9e80E19ue8pYFfxTHYLLxX2iCbMG9ienGP5ROFQjHy2ss14oXv8VAPRSf/MnSW0I6k0emeJhjnXz6unCmqj7ZoJ7L4Xar6DI9T3TigmQIUy4coMvkQSCwPNrvj6SHDK4/dimR4YIzT/yw3kp9pC2IWrmnpdwgWHlfKLR3J5bYdB639GLuAU+koxhH6c8c="

